# Generated by Django 4.2.27 on 2026-02-14 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinhoitem',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to=settings.AUTH_USER_MODEL),
        ),
    ]
