# Generated by Django 4.2.27 on 2026-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_carrinhoitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
